# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~ServiceBricks.Xunit.Integration" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover
    - name: Merge Test Results to Get Overall Code Coverage
      run: dotnet test src/V1/Tests/ServiceBricks.Logging.InMemory.XunitNet9 --no-build --verbosity normal --filter "FullyQualifiedName!~ServiceBricks.Xunit.Integration" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=\"json,opencover\" -p:MergeWith="../ServiceBricks.Logging.XunitNet9/TestResults/coverage.json"
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: purple
        path: src/V1/Tests/ServiceBricks.Logging.InMemory.XunitNet9/TestResults/coverage.opencover.xml
        gist-filename: servicebrickslogging-codecoverage.json
        gist-id: 2214c3b2c703476cbafeb647eb655fc8
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }} 
